[package]
name = "deepbook_wrapper"
version = "0.0.4"
edition = "2024.beta"

[dependencies]
# Mainnet version
deepbook = { local = "../deepbook", address = "0xcaf6ba059d539a97646d47f0b9ddf843e138d215e2a12ca1f4585d386f7aec3a" }
token = { local = "../token", address = "0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270" }

# DeepBook V3 dependencies with specific commit
# deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "197b5339e69fb95ffce64994869b1b61dcb56c8d" }
# token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "197b5339e69fb95ffce64994869b1b61dcb56c8d" }

[addresses]
deepbook_wrapper = "0x4af08dd22015fdabeae5f2b883dca9fca4f7de88434dae7cea712d247658b68d"
# deepbook_wrapper = "0x0"
