[package]
name = "deepbook_wrapper"
version = "0.0.4"
edition = "2024.beta"

[dependencies]
# Mainnet version
deepbook = { local = "../deepbook", address = "0xcaf6ba059d539a97646d47f0b9ddf843e138d215e2a12ca1f4585d386f7aec3a" }

[addresses]
deepbook_wrapper = "0x2356885eae212599c0c7a42d648cc2100dedfa4698f8fc58fc6b9f67806f2bfc"
# deepbook_wrapper = "0x0"
